version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - ../:/workspace:cached
      - ${HOME}/.ssh:/root/.ssh
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434

volumes:
  ollama: {}
