name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go install github.com/yusufcanb/tlm

      - name: Build
        run: bash build.sh $(cat VERSION)

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
