name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get github.com/yusufcanb/tlama
      - name: Build
        run: go build -v cmd/...
      - name: Test with the Go CLI
        run: go test
