name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get ./...
        env:
          GOPATH: /opt/hostedtoolcache/go

      - name: Build
        run: go build -v cmd/cli.go
        env:
          GOPATH: /opt/hostedtoolcache/go

      - name: Test with the Go CLI
        run: go test
        env:
          GOPATH: /opt/hostedtoolcache/go
