name: e2e

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Install tlm
        run: |
          mv dist/tlm_1.1_linux_amd64 /usr/local/bin/tlm 
          chmod +x /usr/local/bin/tlm

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r e2e/requirements.txt

      - name: Run Robot Framework
        run: robot --outputdir dist --name tlm --exclude requires=ollama .\tests\

      - name: Archive report.html
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: e2e/dist/report.html

      - name: Archive log.html
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: e2e/dist/log.html
